//! Tauri build script + embedded web-remote panel.
//!
//! The panel is a separate Vite build (`bun run remote:build` →
//! `src-tauri/remote-dist/`). This script walks that directory and emits an
//! `include_bytes!` table so the release binary serves the panel without any
//! runtime files. A missing dist (fresh clone, `cargo check` before the
//! frontend build) simply produces an empty table — the server then answers
//! 503 with a build hint instead of failing the compile.

use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();
    generate_remote_assets();
}

fn generate_remote_assets() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let dist = manifest_dir.join("remote-dist");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("remote_assets.rs");

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut files);
    }
    files.sort();

    let mut code = String::from(
        "// generated by build.rs — embedded web-remote panel assets\n\
         pub static REMOTE_ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (rel, path) in &files {
        let url = format!("/{}", rel.replace('\\', "/"));
        let absolute = path.to_string_lossy().replace('\\', "/");
        code.push_str(&format!(
            "    (\"{url}\", include_bytes!(r#\"{absolute}\"#)),\n"
        ));
    }
    code.push_str("];\n");

    std::fs::write(&out, code).expect("failed to write remote asset table");
    // Recursively tracked by cargo: any panel rebuild re-embeds the assets.
    println!("cargo:rerun-if-changed=remote-dist");
}

fn collect(root: &Path, dir: &Path, files: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, files);
        } else if let Ok(rel) = path.strip_prefix(root) {
            files.push((rel.to_string_lossy().to_string(), path.clone()));
        }
    }
}
